spring:
  profiles:
    active: dev

  jpa:
    open-in-view: true

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}