version: '3.1'

services:
  products_api:
    image: arturbertoni/product_image:v1
    restart: always
    ports:
      - 8080:8080
    environment:
      URL_POSTGRES: db_products_api
      URL_POSTGRES_PORT: 5432
    depends_on:
      - db_products_api

  db_products_api:
    container_name: db_products_api
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: desafio2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12022004abs
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge