version: '3.1'

services:

  products_api:
    container_name: produto-api
    image: product_image:v1
    restart: always
    ports:
      - "8080:8080"
    environment:
      - URL_POSTGRES=jdbc:postgresql://db_products_api:5432/desafio2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12022004abs
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - db_products_api

  db_products_api:
    container_name: db_produto-api
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=produto-api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12022004abs