version: '3.1'

services:

  products_api:
    container_name: produto-api
    image: arturbertoni/produto-api:v1
    restart: always
    ports:
      - "8080:8080"
    environment:
      - URL_POSTGRES=jdbc:postgresql://db_products_api:5432/produto-api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12022004abs
    depends_on:
      - db_products_api

  db_products_api:
    container_name: db_produto_api
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=produto-api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12022004abs